syntax on
set nocompatible

filetype on
filetype indent on

set autoindent
set smartindent

set tabstop=4
set shiftwidth=4
set expandtab

set incsearch
set ignorecase
set smartcase
set hlsearch

set nu

set hls is

let python_highlight_all = 1
let python_print_as_function = 1
let python_slow_sync = 1

au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") |
                         \ exe "normal g'\"" | endif

autocmd BufRead,BufNew,BufNewFile *.xsd,*.zcml,*.pt,*.kid set filetype=xml